# Generated by Django 5.2.3 on 2025-07-08 22:22

import django.db.models.deletion
import django_ckeditor_5.fields
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('main_image', models.ImageField(upload_to='activities/main/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('image_of_video', models.ImageField(upload_to='activities/video_img/')),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='name')),
                ('days', models.PositiveIntegerField()),
                ('nights', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_name', models.CharField(max_length=255)),
                ('location_link', models.URLField()),
                ('stars', models.PositiveIntegerField()),
                ('reviews', models.PositiveIntegerField()),
                ('love', models.PositiveIntegerField()),
                ('details', django_ckeditor_5.fields.CKEditor5Field(verbose_name='details')),
                ('overviews', django_ckeditor_5.fields.CKEditor5Field(verbose_name='overviews')),
                ('ages', models.CharField(max_length=50)),
                ('max_groups', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('start_time', models.TimeField()),
                ('included', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('datebooking', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_people', models.PositiveIntegerField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('activities', models.ManyToManyField(related_name='categories', to='activities.activity')),
                ('text', models.ManyToManyField(related_name='activity_category_texts', to='core.translatedtext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('img', models.ImageField(upload_to='activities/gallery/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(verbose_name='comment')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='activities.activitybooking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
