# Generated by Django 5.2.3 on 2025-07-18 11:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='included',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='included'),
        ),
    ]
