# Generated by Django 5.2.3 on 2025-07-18 11:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(unique=True, verbose_name='name'),
        ),
    ]
