# Generated by Django 5.2.3 on 2025-07-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingperson',
            old_name='number',
            new_name='phone',
        ),
    ]
