# Generated by Django 5.2.3 on 2025-07-06 03:09

import django.db.models.deletion
import django_ckeditor_5.fields
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('visa_type', models.CharField(choices=[('free', 'Visa Free'), ('evisa', 'E-Visa'), ('other', 'Other')], max_length=10)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField()),
                ('flight_info', django_ckeditor_5.fields.CKEditor5Field(verbose_name='flight_info')),
                ('hotel_info', django_ckeditor_5.fields.CKEditor5Field(verbose_name='hotel_info')),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_people', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('flag_image', models.ImageField(upload_to='flags/')),
                ('visa_type', models.CharField(choices=[('free', 'Visa Free'), ('evisa', 'E-Visa'), ('other', 'Other')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='person_images/')),
                ('address', models.TextField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('visa_image', models.ImageField(upload_to='visa_docs/')),
                ('age', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='visa.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.country'),
        ),
        migrations.CreateModel(
            name='VisaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='visa_cards/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.country')),
                ('text', models.ManyToManyField(related_name='visa_titles', to='core.translatedtext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('section_name', models.CharField(max_length=100)),
                ('cards', models.ManyToManyField(related_name='visa_sections', to='visa.visacard')),
                ('text', models.ManyToManyField(related_name='section_titles', to='core.translatedtext')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
