# Generated by Django 5.2.3 on 2025-07-11 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.country'),
        ),
    ]
