# Generated by Django 5.2.3 on 2025-07-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_remove_booking_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='visa_type',
        ),
    ]
