# Generated by Django 5.2.3 on 2025-07-11 05:07

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_remove_booking_price_remove_booking_visa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(upload_to='flags/', verbose_name='flag'),
        ),
        migrations.AlterField(
            model_name='country',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa_type',
            field=models.CharField(choices=[('free', 'Visa Free'), ('evisa', 'E-Visa'), ('other', 'Other')], max_length=10, verbose_name='type of visa'),
        ),
    ]
