# Generated by Django 5.2.3 on 2025-07-11 05:33

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('visa', '0005_alter_country_country_alter_country_flag_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingperson',
            options={'verbose_name': 'Booking person', 'verbose_name_plural': 'Booking persons'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='visacard',
            options={'verbose_name': 'visa card', 'verbose_name_plural': 'visa cards'},
        ),
        migrations.AlterModelOptions(
            name='visasection',
            options={'verbose_name': 'visa section', 'verbose_name_plural': 'visa sections'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(verbose_name='adults'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(verbose_name='children'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_info',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='info of flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_info',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='info of hotels'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(verbose_name='date of return'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_people',
            field=models.PositiveIntegerField(verbose_name='total people'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(verbose_name='date of travel'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='address',
            field=models.TextField(verbose_name='address of person'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='age',
            field=models.PositiveIntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='visa.booking', verbose_name='which booking'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='image',
            field=models.ImageField(upload_to='person_images/', verbose_name='image of person'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.country', verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='visa_image',
            field=models.ImageField(upload_to='visa_docs/', verbose_name='image of visa'),
        ),
        migrations.AlterField(
            model_name='visacard',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='visacard',
            name='image',
            field=models.ImageField(upload_to='visa_cards/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='visacard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='type of visa'),
        ),
        migrations.AlterField(
            model_name='visacard',
            name='text',
            field=models.ManyToManyField(related_name='visa_titles', to='core.translatedtext', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='visasection',
            name='cards',
            field=models.ManyToManyField(related_name='visa_sections', to='visa.visacard', verbose_name='which card'),
        ),
        migrations.AlterField(
            model_name='visasection',
            name='section_name',
            field=models.CharField(max_length=100, verbose_name='name of section'),
        ),
        migrations.AlterField(
            model_name='visasection',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='type of visa'),
        ),
        migrations.AlterField(
            model_name='visasection',
            name='text',
            field=models.ManyToManyField(related_name='section_titles', to='core.translatedtext', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='visasection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='type of visa'),
        ),
    ]
