# Generated by Django 5.2.3 on 2025-07-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_alter_booking_options_alter_bookingperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/', verbose_name='image of person'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='visa_image',
            field=models.ImageField(blank=True, null=True, upload_to='visa_docs/', verbose_name='image of visa'),
        ),
    ]
