# Generated by Django 5.2.3 on 2025-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0007_alter_bookingperson_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='person_images/', verbose_name='image of person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='visa_image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='visa_docs/', verbose_name='image of visa'),
            preserve_default=False,
        ),
    ]
