# Generated by Django 5.2.3 on 2025-07-18 16:58

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_newsletter'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('link_location', models.URLField(blank=True, null=True, verbose_name='link of location')),
                ('location_name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='location_name')),
                ('description', models.ManyToManyField(related_name='find_us_descriptions', to='core.translatedtext', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Find_Us',
                'verbose_name_plural': 'Find_Us',
            },
        ),
        migrations.CreateModel(
            name='Get_In_Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.ManyToManyField(related_name='get_in_touch_descriptions', to='core.translatedtext', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Get_In_Touch',
                'verbose_name_plural': 'Get_In_Touch',
            },
        ),
    ]
