# Generated by Django 5.2.3 on 2025-07-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_inside_360',
            field=models.ImageField(blank=True, null=True, upload_to='cars/inside360/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_open_door_360',
            field=models.ImageField(blank=True, null=True, upload_to='cars/door360/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_outside_360',
            field=models.ImageField(blank=True, null=True, upload_to='cars/outside360/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/main/'),
        ),
    ]
