# Generated by Django 5.2.3 on 2025-07-18 11:32

import django.db.models.deletion
import django_ckeditor_5.fields
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_image_inside_360_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingperson',
            options={'verbose_name': 'Booking Person', 'verbose_name_plural': 'Booking Persons'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carbooking',
            options={'verbose_name': 'Car Booking', 'verbose_name_plural': 'Car Bookings'},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name': 'Car category', 'verbose_name_plural': 'Car categories'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Car Image', 'verbose_name_plural': 'Car Images'},
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='age',
            field=models.PositiveIntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='cars.carbooking', verbose_name='booking'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='car',
            name='child_safety_seat',
            field=models.BooleanField(default=False, verbose_name='child safety seat'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=10, verbose_name='type of fuel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10, verbose_name='type of gear'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_inside_360',
            field=models.ImageField(default=1, upload_to='cars/inside360/', verbose_name='inside img of car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image_open_door_360',
            field=models.ImageField(default='cars/360/default.jpg', upload_to='cars/door360/', verbose_name='open door img of car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image_outside_360',
            field=models.ImageField(default='cars/360/default.jpg', upload_to='cars/outside360/', verbose_name='outside img of car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(default='cars/360/default.jpg', upload_to='cars/main/', verbose_name='main img of car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(verbose_name='year of model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.ManyToManyField(related_name='car_names', to='core.translatedtext', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per day'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per hour'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(verbose_name='seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='zero_to_100_seconds',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='zero to 100 seconds'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='adults',
            field=models.PositiveIntegerField(verbose_name='adults'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='children',
            field=models.PositiveIntegerField(verbose_name='children'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='flight_info',
            field=models.TextField(verbose_name='flight info'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='hotel_info',
            field=models.TextField(verbose_name='hotel info'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='meeting_point',
            field=models.CharField(max_length=255, verbose_name='meeting point'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='return_date',
            field=models.DateField(verbose_name='date of return'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='total_people',
            field=models.PositiveIntegerField(verbose_name='total people'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='travel_date',
            field=models.DateField(verbose_name='date of travel'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='trip_type',
            field=models.CharField(choices=[('pickup', 'استقبال مطار'), ('dropoff', 'توديع مطار'), ('both', 'استقبال وتوديع'), ('all', 'الكل')], max_length=10, verbose_name='type of trip'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='car',
            field=models.ManyToManyField(related_name='category_cars', to='cars.car', verbose_name='category car'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='description',
            field=models.ManyToManyField(related_name='car_category_descs', to='core.translatedtext', verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_car', to='cars.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/gallery/', verbose_name='image of cars'),
        ),
    ]
